export const PATH_CREATE_STAFF = '/staff'
export const PATH_GET_STAFF_PAGINATION = '/staff/pagination'
export const PATH_USER = '/user'
export const PATH_GET_USER = '/user/:username'
export const PATH_GET_USER_PAGINAtION = '/user/pagination'
export const PATH_LOGIN = '/login'
export const PATH_CREATE_MENU_OPTION = '/menu_options'
export const PATH_GET_MENU_OPTION_WITH_PERMISSIONS =
  '/menu_options/get_with_permission'
export const PATH_GET_USER_MENU_OPTIONS = '/menu_options/:username'
export const PATH_GET_ROLE_PAGINATION = '/role/pagination'
export const PATH_CREATE_UPDATE_ROLE = '/role'
export const PATH_GET_PERMISSIONS_PAGINATION = '/permissions/pagination'
