import { MigrationInterface, QueryRunner } from 'typeorm'

export class UpdateGoalTasks1762200000000 implements MigrationInterface {
  name = 'UpdateGoalTasks1762200000000'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM information_schema.columns
          WHERE table_name = 'GOAL_TASK'
            AND column_name = 'GOAL_MODULE_ID'
        ) THEN
          ALTER TABLE "GOAL_TASK"
            ADD COLUMN "GOAL_MODULE_ID" integer;
        END IF;
      END $$;
    `)

    await queryRunner.query(`
      DO $$
      DECLARE
        seq_name text;
        max_id bigint;
        new_value bigint;
        seq_called boolean;
      BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM information_schema.columns
          WHERE table_name = 'GOAL_TASK'
            AND column_name = 'GOAL_TASK_ID'
            AND is_identity = 'YES'
        ) THEN
          ALTER TABLE "GOAL_TASK"
            ALTER COLUMN "GOAL_TASK_ID" DROP DEFAULT;
          ALTER TABLE "GOAL_TASK"
            ALTER COLUMN "GOAL_TASK_ID" ADD GENERATED BY DEFAULT AS IDENTITY;
          SELECT pg_get_serial_sequence('"GOAL_TASK"', 'GOAL_TASK_ID')
            INTO seq_name;
          SELECT COALESCE(MAX("GOAL_TASK_ID"), 0)
            INTO max_id
            FROM "GOAL_TASK";
          new_value := GREATEST(max_id, 1);
          seq_called := max_id > 0;
          IF seq_name IS NOT NULL THEN
            EXECUTE format(
              'SELECT setval(%L, %s, %s)',
              seq_name,
              new_value,
              CASE WHEN seq_called THEN 'true' ELSE 'false' END
            );
          END IF;
        END IF;
      END $$;
    `)

    await queryRunner.query(`
      DO $$
      DECLARE
        seq_name text;
        max_id bigint;
        new_value bigint;
        seq_called boolean;
      BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM information_schema.columns
          WHERE table_name = 'GOAL_TASK_X_STAFF'
            AND column_name = 'GOAL_TASK_STAFF_ID'
            AND is_identity = 'YES'
        ) THEN
          ALTER TABLE "GOAL_TASK_X_STAFF"
            ALTER COLUMN "GOAL_TASK_STAFF_ID" DROP DEFAULT;
          ALTER TABLE "GOAL_TASK_X_STAFF"
            ALTER COLUMN "GOAL_TASK_STAFF_ID" ADD GENERATED BY DEFAULT AS IDENTITY;
          SELECT pg_get_serial_sequence('"GOAL_TASK_X_STAFF"', 'GOAL_TASK_STAFF_ID')
            INTO seq_name;
          SELECT COALESCE(MAX("GOAL_TASK_STAFF_ID"), 0)
            INTO max_id
            FROM "GOAL_TASK_X_STAFF";
          new_value := GREATEST(max_id, 1);
          seq_called := max_id > 0;
          IF seq_name IS NOT NULL THEN
            EXECUTE format(
              'SELECT setval(%L, %s, %s)',
              seq_name,
              new_value,
              CASE WHEN seq_called THEN 'true' ELSE 'false' END
            );
          END IF;
        END IF;
      END $$;
    `)

    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM information_schema.table_constraints
          WHERE constraint_name = 'FK_GOAL_TASK_STAFF_STAFF'
        ) THEN
          ALTER TABLE "GOAL_TASK_X_STAFF"
            ADD CONSTRAINT "FK_GOAL_TASK_STAFF_STAFF"
            FOREIGN KEY ("STAFF_ID")
            REFERENCES "STAFF"("STAFF_ID")
            ON DELETE NO ACTION ON UPDATE NO ACTION;
        END IF;
      END $$;
    `)

    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1
          FROM information_schema.table_constraints
          WHERE constraint_name = 'FK_GOAL_TASK_GOAL_MODULE'
        ) THEN
          ALTER TABLE "GOAL_TASK"
            ADD CONSTRAINT "FK_GOAL_TASK_GOAL_MODULE"
            FOREIGN KEY ("GOAL_MODULE_ID")
            REFERENCES "GOAL_X_MODULE"("GOAL_MODULE_ID")
            ON DELETE CASCADE ON UPDATE NO ACTION;
        END IF;
      END $$;
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "GOAL_TASK" DROP CONSTRAINT IF EXISTS "FK_GOAL_TASK_GOAL_MODULE"`
    )
    await queryRunner.query(
      `ALTER TABLE "GOAL_TASK" DROP COLUMN IF EXISTS "GOAL_MODULE_ID"`
    )
    await queryRunner.query(
      `ALTER TABLE "GOAL_TASK_X_STAFF" DROP CONSTRAINT IF EXISTS "FK_GOAL_TASK_STAFF_STAFF"`
    )
    await queryRunner.query(
      `ALTER TABLE "GOAL_TASK_X_STAFF" ALTER COLUMN "GOAL_TASK_STAFF_ID" DROP IDENTITY IF EXISTS`
    )
    await queryRunner.query(
      `ALTER TABLE "GOAL_TASK" ALTER COLUMN "GOAL_TASK_ID" DROP IDENTITY IF EXISTS`
    )
  }
}
